"""add deleted_at and delete_after to answerupload

Revision ID: 18ac0e23ddf7
Revises: e03fd2104ce9
Create Date: 2026-09-17 11:52:14.115548

"""

# revision identifiers, used by Alembic.
revision = "18ac0e23ddf7"
down_revision = "e03fd2104ce9"

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("answerupload", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True)
        )
        batch_op.add_column(
            sa.Column("delete_after", sa.DateTime(timezone=True), nullable=True)
        )
        batch_op.create_index(
            batch_op.f("ix_answerupload_delete_after"), ["delete_after"], unique=False
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("answerupload", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_answerupload_delete_after"))
        batch_op.drop_column("delete_after")
        batch_op.drop_column("deleted_at")

    # ### end Alembic commands ###
